"""empty message

Revision ID: 18d53582961e
Revises: 
Create Date: 2020-11-18 20:28:49.501731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18d53582961e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('currency', sa.String(length=8), nullable=True))
    op.add_column('product', sa.Column('price', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_product_currency'), 'product', ['currency'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_currency'), table_name='product')
    op.drop_column('product', 'price')
    op.drop_column('product', 'currency')
    # ### end Alembic commands ###
