"""empty message

Revision ID: 38bff9ed6641
Revises: 18d53582961e
Create Date: 2020-11-20 18:37:20.277251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38bff9ed6641'
down_revision = '18d53582961e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('units_sold', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'units_sold')
    op.drop_column('product', 'quantity')
    # ### end Alembic commands ###
